import os

def patch_file(filepath, replacements):
    with open(filepath, 'r') as f:
        content = f.read()
    for old, new in replacements:
        if old in content:
            content = content.replace(old, new)
        else:
            print(f"Warning: {old[:30]} not found in {filepath}")
    with open(filepath, 'w') as f:
        f.write(content)

cursor_replacements = [
    (
        "Image::~Image()\n{\n  if (hCursor)\n    DestroyCursor(hCursor);\n  hCursor = 0;\n}",
        "Image::~Image()\n{\n#ifndef NV_LINUX_PLATFORM\n  if (hCursor)\n    DestroyCursor(hCursor);\n#endif\n  hCursor = 0;\n}"
    ),
    (
        "static const char * FormatLastLastErrorMessage( DWORD errorCode )\n{\n  static char buffer[512] = \"\";\n  if ( FormatMessage( FORMAT_MESSAGE_FROM_SYSTEM, 0, errorCode, 0, buffer, 512, 0 ) )\n    return buffer;\n  else\n    return \"Eror message not found\";\n}",
        "static const char * FormatLastLastErrorMessage( DWORD errorCode )\n{\n#ifndef NV_LINUX_PLATFORM\n  static char buffer[512] = \"\";\n  if ( FormatMessage( FORMAT_MESSAGE_FROM_SYSTEM, 0, errorCode, 0, buffer, 512, 0 ) )\n    return buffer;\n  else\n#endif\n    return \"Eror message not found\";\n}"
    ),
    (
        "static bool CreateCursors( SCursor *pCursor, const Image & image )\n{\n\tif ( !pCursor )\n\t\treturn false;\n\n  if ( pCursor->hCursor || pCursor->hCursor16 || pCursor->hCursor24 || pCursor->hCursor32 )\n  {\n    NI_ALWAYS_ASSERT(\"Try REcreate exist cursor\");\n    pCursor->ReleaseResources();\n  }\n\n  PushDXPoolGuard dxPool(\"UI\");\n\n  // separate processing for precompiled cursor\n  if (image.GetHandle())\n  {\n    pCursor->hCursor = image.GetHandle();\n    pCursor->hCursor16 = 0;\n    pCursor->hCursor24 = 0;\n    pCursor->hCursor32 = image.GetCursorPic();\n    pCursor->pTexture = 0;\n    return true;\n  }\n\n\tconst CArray2D<DWORD> & data = image.GetData();\n\n\tconst int cw = image.GetWidth();\n\tconst int ch = image.GetHeight();",
        "static bool CreateCursors( SCursor *pCursor, const Image & image )\n{\n\tif ( !pCursor )\n\t\treturn false;\n\n  if ( pCursor->hCursor || pCursor->hCursor16 || pCursor->hCursor24 || pCursor->hCursor32 )\n  {\n    NI_ALWAYS_ASSERT(\"Try REcreate exist cursor\");\n    pCursor->ReleaseResources();\n  }\n\n  PushDXPoolGuard dxPool(\"UI\");\n\n  // separate processing for precompiled cursor\n  if (image.GetHandle())\n  {\n    pCursor->hCursor = image.GetHandle();\n    pCursor->hCursor16 = 0;\n    pCursor->hCursor24 = 0;\n    pCursor->hCursor32 = image.GetCursorPic();\n    pCursor->pTexture = 0;\n    return true;\n  }\n\n\tconst CArray2D<DWORD> & data = image.GetData();\n\n\tconst int cw = image.GetWidth();\n\tconst int ch = image.GetHeight();\n#ifndef NV_LINUX_PLATFORM"
    ),
    (
        "\n\treturn true;\n}\n\n//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////\nvoid ReleaseCursors( SCursor *pCursor )\n",
        "\n#endif\n\treturn true;\n}\n\n//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////\nvoid ReleaseCursors( SCursor *pCursor )\n"
    ),
    (
        "void Freeze( bool f )\n\t{\n\t\tg_freezeUpdate = f;\n\n\t\tif ( g_freezeUpdate )\n\t\t{\n\t\t\t::ClipCursor(0);\n\n\t\t\tHWND hWnd = NMainFrame::GetWnd();\n\n\t\t\tif ( !hWnd )\n\t\t\t{\n\t\t\t\tg_freezePos.x = 0;\n\t\t\t\tg_freezePos.y = 0;\n\t\t\t}\n\t\t\telse\n\t\t\t{\n\t\t\t\tif ( FAILED( ::GetCursorPos( &g_freezePos ) ) )\n\t\t\t\t{\n\t\t\t\t\tg_freezePos.x = 0;\n\t\t\t\t\tg_freezePos.y = 0;\n\t\t\t\t}\n\t\t\t\t::GetClipCursor( &g_freezeClip );\n\t\t\t}\n\t\t}\n\t}",
        "void Freeze( bool f )\n\t{\n\t\tg_freezeUpdate = f;\n\n\t\tif ( g_freezeUpdate )\n\t\t{\n#ifndef NV_LINUX_PLATFORM\n\t\t\t::ClipCursor(0);\n\n\t\t\tHWND hWnd = NMainFrame::GetWnd();\n\n\t\t\tif ( !hWnd )\n\t\t\t{\n\t\t\t\tg_freezePos.x = 0;\n\t\t\t\tg_freezePos.y = 0;\n\t\t\t}\n\t\t\telse\n\t\t\t{\n\t\t\t\tif ( FAILED( ::GetCursorPos( &g_freezePos ) ) )\n\t\t\t\t{\n\t\t\t\t\tg_freezePos.x = 0;\n\t\t\t\t\tg_freezePos.y = 0;\n\t\t\t\t}\n\t\t\t\t::GetClipCursor( &g_freezeClip );\n\t\t\t}\n#endif\n\t\t}\n\t}"
    ),
    (
        "void Update( DWORD newTime )\n\t{\n\t\tif ( g_freezeUpdate )\n\t\t{\n\t\t\tHWND hWnd = NMainFrame::GetWnd();\n\n\t\t\tif ( hWnd && hWnd == ::GetFocus() )\n\t\t\t{\n\t\t\t\t\t::ClipCursor(0);\n\n\t\t\t\t\tPOINT pt;\n\t\t\t\t\tif ( SUCCEEDED( ::GetCursorPos( &pt ) ) && ( pt.x != g_freezePos.x || pt.y != g_freezePos.y ) )\n\t\t\t\t\t{\n\t\t\t\t\t\t::SetCursorPos( g_freezePos.x, g_freezePos.y );\n\t\t\t\t\t\t::ClipCursor( &g_freezeClip );\n\t\t\t\t\t}\n\t\t\t}\n\t\t}\n\n\t\tHDC hdc = GetDC( NMainFrame::GetWnd() );\n\t\tconst int displayBits = GetDeviceCaps( hdc, BITSPIXEL );\n\t\tReleaseDC( NMainFrame::GetWnd(), hdc );\n\n\t\tg_displayBits = displayBits;\n\n\t\tif ( g_cursorSmooth == \"auto\" || g_cursorSmooth == \"false\" )\n\t\t{\n\t\t\tg_cursorHW = true;\n\t\t}\n\n\t\tif ( g_cursorSmooth == \"true\" )\n\t\t{\n\t\t\tg_cursorHW = false;\n\t\t}\n\n\t\tif ( !g_cursorHW && !g_cursorSWInited )\n\t\t{\n\t\t\tInitSWCursors();\n\t\t}\n\n\t\tif ( g_cursorsCacheHead <= 1 )\n\t\t\treturn;\n\n\t\tSCursor * pCursor = &g_cursorsCache[ g_currentCacheRef ];\n\n\t\t//if ( pCursor->pTexture )\n\t\t{\n\t\t\tif ( g_cursorHW )\n\t\t\t{\n\t\t\t\tif ( displayBits == 32 && pCursor->hCursor32 )\n\t\t\t\t\tNMainFrame::SetCursor( pCursor->hCursor32 );\n\t\t\t\telse if ( displayBits == 16 && pCursor->hCursor16 )\n\t\t\t\t\tNMainFrame::SetCursor( pCursor->hCursor16 );\n\t\t\t\telse if ( pCursor->hCursor24 )\n\t\t\t\t\tNMainFrame::SetCursor( pCursor->hCursor24 );\n        else if ( pCursor->hCursor )\n          NMainFrame::SetCursor( pCursor->hCursor );\n\t\t\t\telse\n\t\t\t\t\tNMainFrame::SetCursor( LoadCursor( NULL, IDC_ARROW ) );\n\t\t\t}\n\t\t\telse\n\t\t\t{\n\t\t\t\tNMainFrame::SetCursor( NULL );\n\t\t\t}\n\t\t}\n\t}",
        "void Update( DWORD newTime )\n\t{\n#ifndef NV_LINUX_PLATFORM\n\t\tif ( g_freezeUpdate )\n\t\t{\n\t\t\tHWND hWnd = NMainFrame::GetWnd();\n\n\t\t\tif ( hWnd && hWnd == ::GetFocus() )\n\t\t\t{\n\t\t\t\t\t::ClipCursor(0);\n\n\t\t\t\t\tPOINT pt;\n\t\t\t\t\tif ( SUCCEEDED( ::GetCursorPos( &pt ) ) && ( pt.x != g_freezePos.x || pt.y != g_freezePos.y ) )\n\t\t\t\t\t{\n\t\t\t\t\t\t::SetCursorPos( g_freezePos.x, g_freezePos.y );\n\t\t\t\t\t\t::ClipCursor( &g_freezeClip );\n\t\t\t\t\t}\n\t\t\t}\n\t\t}\n\n\t\tHDC hdc = GetDC( NMainFrame::GetWnd() );\n\t\tconst int displayBits = GetDeviceCaps( hdc, BITSPIXEL );\n\t\tReleaseDC( NMainFrame::GetWnd(), hdc );\n\n\t\tg_displayBits = displayBits;\n#endif\n\t\tif ( g_cursorSmooth == \"auto\" || g_cursorSmooth == \"false\" )\n\t\t{\n\t\t\tg_cursorHW = true;\n\t\t}\n\n\t\tif ( g_cursorSmooth == \"true\" )\n\t\t{\n\t\t\tg_cursorHW = false;\n\t\t}\n\n\t\tif ( !g_cursorHW && !g_cursorSWInited )\n\t\t{\n\t\t\tInitSWCursors();\n\t\t}\n\n\t\tif ( g_cursorsCacheHead <= 1 )\n\t\t\treturn;\n\n\t\tSCursor * pCursor = &g_cursorsCache[ g_currentCacheRef ];\n\n\t\t//if ( pCursor->pTexture )\n\t\t{\n\t\t\tif ( g_cursorHW )\n\t\t\t{\n#ifndef NV_LINUX_PLATFORM\n\t\t\t\tif ( g_displayBits == 32 && pCursor->hCursor32 )\n\t\t\t\t\tNMainFrame::SetCursor( pCursor->hCursor32 );\n\t\t\t\telse if ( g_displayBits == 16 && pCursor->hCursor16 )\n\t\t\t\t\tNMainFrame::SetCursor( pCursor->hCursor16 );\n\t\t\t\telse if ( pCursor->hCursor24 )\n\t\t\t\t\tNMainFrame::SetCursor( pCursor->hCursor24 );\n        else if ( pCursor->hCursor )\n          NMainFrame::SetCursor( pCursor->hCursor );\n\t\t\t\telse\n\t\t\t\t\tNMainFrame::SetCursor( LoadCursor( NULL, IDC_ARROW ) );\n#endif\n\t\t\t}\n\t\t\telse\n\t\t\t{\n#ifndef NV_LINUX_PLATFORM\n\t\t\t\tNMainFrame::SetCursor( NULL );\n#endif\n\t\t\t}\n\t\t}\n\t}"
    ),
    (
        "void Render()\n\t{\n\t\tif ( g_cursorHW || g_cursorsCacheHead <= 1 || !NMainFrame::GetWnd() || ::GetFocus() != NMainFrame::GetWnd() || !Render::GetRenderParams().showCursor )\n\t\t\treturn;\n\n\t\tPOINT pt;\n\t\tif ( TRUE != GetCursorPos( &pt ) )\n\t\t\treturn;\n\n\t\tRECT r;\n\t\tif ( TRUE != GetClientRect( NMainFrame::GetWnd(), &r ) )\n\t\t\treturn;\n\n\t\tif ( pt.x < r.left || pt.y < r.top || pt.x > r.right || pt.y > r.bottom )\n\t\t\treturn;\n\n\t\tPOINT leftTop = { 0, 0 };\n\t\tif ( TRUE != ClientToScreen( NMainFrame::GetWnd(), &leftTop ) )\n\t\t\treturn;\n\n\t\tpt.x -= leftTop.x;\n\t\tpt.y -= leftTop.y;",
        "void Render()\n\t{\n#ifndef NV_LINUX_PLATFORM\n\t\tif ( g_cursorHW || g_cursorsCacheHead <= 1 || !NMainFrame::GetWnd() || ::GetFocus() != NMainFrame::GetWnd() || !Render::GetRenderParams().showCursor )\n\t\t\treturn;\n\n\t\tPOINT pt;\n\t\tif ( TRUE != GetCursorPos( &pt ) )\n\t\t\treturn;\n\n\t\tRECT r;\n\t\tif ( TRUE != GetClientRect( NMainFrame::GetWnd(), &r ) )\n\t\t\treturn;\n\n\t\tif ( pt.x < r.left || pt.y < r.top || pt.x > r.right || pt.y > r.bottom )\n\t\t\treturn;\n\n\t\tPOINT leftTop = { 0, 0 };\n\t\tif ( TRUE != ClientToScreen( NMainFrame::GetWnd(), &leftTop ) )\n\t\t\treturn;\n\n\t\tpt.x -= leftTop.x;\n\t\tpt.y -= leftTop.y;\n#else\n\t\tif ( g_cursorHW || g_cursorsCacheHead <= 1 || !Render::GetRenderParams().showCursor )\n\t\t\treturn;\n\t\tPOINT pt = {0,0};\n#endif"
    ),
    (
        "void* LoadPrecompiledCursor(const nstl::string & fileName)\n{\n  const nstl::string tempName = NFile::GetRootPath() + fileName;\n  HCURSOR hCursor = reinterpret_cast<HCURSOR>(::LoadImage(NULL, tempName.c_str(), IMAGE_CURSOR, 0, 0, LR_LOADFROMFILE));\n  return hCursor;\n}",
        "void* LoadPrecompiledCursor(const nstl::string & fileName)\n{\n#ifndef NV_LINUX_PLATFORM\n  const nstl::string tempName = NFile::GetRootPath() + fileName;\n  HCURSOR hCursor = reinterpret_cast<HCURSOR>(::LoadImage(NULL, tempName.c_str(), IMAGE_CURSOR, 0, 0, LR_LOADFROMFILE));\n  return hCursor;\n#else\n  return 0;\n#endif\n}"
    ),
    (
        "bool Image::Load(const NDb::UICursorBase * pCursorDesc)\n{\n  if ( !pCursorDesc )\n    return false;\n\n  hCursor = LoadPrecompiledCursor(pCursorDesc->fileName);\n\n  if (hCursor)\n  {\n    ICONINFO ie = { sizeof(ICONINFO) };\n    ::GetIconInfo(hCursor, &ie);\n    \n    // hack: this makes 32-bit alpha blended color bitmap available inside the cursor handle.\n    // because LoadImage( ... LR_LOADFROMFILE ) drops color information leaving mask only \n    // if the cursor doesn't have 32-bit icon available in display settings. \n    hCursorPic = (HCURSOR)CreateIconIndirect( &ie );\n\n    ie.fIcon = FALSE;\n    ::GetIconInfo(hCursorPic, &ie);\n\n    width = 0;\n    height = 0;\n    BITMAP bm = {0};\n    \n    if (ie.hbmColor)\n    {\n      int ok = ::GetObject(ie.hbmColor, sizeof(bm), &bm);\n      if (ok)\n      {\n        width = bm.bmWidth;\n        height = bm.bmHeight;\n      }\n    }\n\n    if (!ie.hbmColor && ie.hbmMask)\n    {\n      // black'n'white cursor have only mask of double height\n      int ok = ::GetObject(ie.hbmMask, sizeof(bm), &bm);\n      if (ok)\n      {\n        width = bm.bmWidth;\n        height = bm.bmHeight/2;\n      }\n    }\n\n    if (ie.hbmMask)\n      DeleteObject(ie.hbmMask);\n    if (ie.hbmColor)\n      DeleteObject(ie.hbmColor);\n\n    return true;\n  }\n\n  pCursorObj = pCursorDesc;",
        "bool Image::Load(const NDb::UICursorBase * pCursorDesc)\n{\n  if ( !pCursorDesc )\n    return false;\n\n  hCursor = LoadPrecompiledCursor(pCursorDesc->fileName);\n\n  if (hCursor)\n  {\n#ifndef NV_LINUX_PLATFORM\n    ICONINFO ie = { sizeof(ICONINFO) };\n    ::GetIconInfo(hCursor, &ie);\n    \n    // hack: this makes 32-bit alpha blended color bitmap available inside the cursor handle.\n    // because LoadImage( ... LR_LOADFROMFILE ) drops color information leaving mask only \n    // if the cursor doesn't have 32-bit icon available in display settings. \n    hCursorPic = (HCURSOR)CreateIconIndirect( &ie );\n\n    ie.fIcon = FALSE;\n    ::GetIconInfo(hCursorPic, &ie);\n\n    width = 0;\n    height = 0;\n    BITMAP bm = {0};\n    \n    if (ie.hbmColor)\n    {\n      int ok = ::GetObject(ie.hbmColor, sizeof(bm), &bm);\n      if (ok)\n      {\n        width = bm.bmWidth;\n        height = bm.bmHeight;\n      }\n    }\n\n    if (!ie.hbmColor && ie.hbmMask)\n    {\n      // black'n'white cursor have only mask of double height\n      int ok = ::GetObject(ie.hbmMask, sizeof(bm), &bm);\n      if (ok)\n      {\n        width = bm.bmWidth;\n        height = bm.bmHeight/2;\n      }\n    }\n\n    if (ie.hbmMask)\n      DeleteObject(ie.hbmMask);\n    if (ie.hbmColor)\n      DeleteObject(ie.hbmColor);\n#endif\n    return true;\n  }\n\n  pCursorObj = pCursorDesc;"
    ),
]

editbox_replacements = [
    (
        "bool EditBox::EventPaste()\n{\n  if ( !IsFocused() )\n    return false;\n\n  if ( !IsClipboardFormatAvailable(CF_UNICODETEXT) ) \n    return true; \n  if ( !OpenClipboard( 0 ) ) \n    return true;\n\n  HANDLE h = GetClipboardData(CF_UNICODETEXT);\n  if ( NULL != h )\n  {\n    LPWSTR lptstr = (LPWSTR)GlobalLock(h); \n    if ( lptstr != NULL ) \n    { \n      wstring Inserted(lptstr);\n      GlobalUnlock(h); \n      CloseClipboard();",
        "bool EditBox::EventPaste()\n{\n  if ( !IsFocused() )\n    return false;\n\n#ifndef NV_LINUX_PLATFORM\n  if ( !IsClipboardFormatAvailable(CF_UNICODETEXT) ) \n    return true; \n  if ( !OpenClipboard( 0 ) ) \n    return true;\n\n  HANDLE h = GetClipboardData(CF_UNICODETEXT);\n  if ( NULL != h )\n  {\n    LPWSTR lptstr = (LPWSTR)GlobalLock(h); \n    if ( lptstr != NULL ) \n    { \n      wstring Inserted(lptstr);\n      GlobalUnlock(h); \n      CloseClipboard();"
    ),
    (
        "      UpdateText();\n      Invalidate();\n    }\n    else\n      CloseClipboard();\n  }\n  else\n    CloseClipboard();\n  return true;\n}",
        "      UpdateText();\n      Invalidate();\n    }\n    else\n      CloseClipboard();\n  }\n  else\n    CloseClipboard();\n#endif\n  return true;\n}"
    ),
    (
        "void EditBox::CopySelectionToClipboard()\n{\n  const int beginSelection = Min( cursorPos, selectionStart );\n  const int endSelection   = Max( cursorPos, selectionStart );\n\n  if ( beginSelection == endSelection )\n    return;\n\n  if ( !OpenClipboard( 0 ) )\n    return;\n\n  EmptyClipboard();\n\n  // copy text to clipboard\n  HGLOBAL hglbCopy = GlobalAlloc(GMEM_MOVEABLE, (endSelection - beginSelection + 1) * sizeof(char));\n  if ( hglbCopy == NULL )\n  {\n    CloseClipboard();\n    return;\n  }\n\n  // TODO: Fix the problem with wchar_t copy (this func expects string not wstring so there is some issues with this clipboard)\n\n  string strSelection = W2A( inputText.substr(beginSelection, endSelection - beginSelection) );\n\n  LPTSTR lptstrCopy = (LPTSTR)GlobalLock( hglbCopy );\n  memcpy( lptstrCopy, strSelection.c_str(), (endSelection - beginSelection) * sizeof(char) );\n  lptstrCopy[endSelection - beginSelection] = (char)0;\n  GlobalUnlock( hglbCopy );\n\n  SetClipboardData( CF_TEXT, hglbCopy );\n  CloseClipboard();\n}",
        "void EditBox::CopySelectionToClipboard()\n{\n  const int beginSelection = Min( cursorPos, selectionStart );\n  const int endSelection   = Max( cursorPos, selectionStart );\n\n  if ( beginSelection == endSelection )\n    return;\n\n#ifndef NV_LINUX_PLATFORM\n  if ( !OpenClipboard( 0 ) )\n    return;\n\n  EmptyClipboard();\n\n  // copy text to clipboard\n  HGLOBAL hglbCopy = GlobalAlloc(GMEM_MOVEABLE, (endSelection - beginSelection + 1) * sizeof(char));\n  if ( hglbCopy == NULL )\n  {\n    CloseClipboard();\n    return;\n  }\n\n  // TODO: Fix the problem with wchar_t copy (this func expects string not wstring so there is some issues with this clipboard)\n\n  string strSelection = W2A( inputText.substr(beginSelection, endSelection - beginSelection) );\n\n  LPTSTR lptstrCopy = (LPTSTR)GlobalLock( hglbCopy );\n  memcpy( lptstrCopy, strSelection.c_str(), (endSelection - beginSelection) * sizeof(char) );\n  lptstrCopy[endSelection - beginSelection] = (char)0;\n  GlobalUnlock( hglbCopy );\n\n  SetClipboardData( CF_TEXT, hglbCopy );\n  CloseClipboard();\n#endif\n}"
    )
]

patch_file("pw/branches/r1117/Src/UI/Cursor.cpp", cursor_replacements)
patch_file("pw/branches/r1117/Src/UI/EditBox.cpp", editbox_replacements)
