/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ClusterManagement_H
#define ClusterManagement_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "ClusterManagementAPI_types.h"

namespace ClusterAdmin { namespace Thrift {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ClusterManagementIf {
 public:
  virtual ~ClusterManagementIf() {}
  virtual void GetServices(std::vector<ServiceInfo> & _return) = 0;
  virtual void GetServicesByMachine(std::vector<ServiceInfo> & _return, const std::string& machine) = 0;
  virtual void GetServicesByType(std::vector<ServiceInfo> & _return, const std::string& stype) = 0;
  virtual void GetServiceById(ServiceInfo& _return, const std::string& serviceid) = 0;
  virtual int32_t ExecuteCommand(const std::string& serviceid, const ServiceCommand::type command, const std::string& arguments) = 0;
  virtual int32_t ChangeParameters(const std::string& serviceid, const std::vector<ServiceParameter> & parameters, const bool saveinconfig) = 0;
};

class ClusterManagementIfFactory {
 public:
  typedef ClusterManagementIf Handler;

  virtual ~ClusterManagementIfFactory() {}

  virtual ClusterManagementIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ClusterManagementIf* /* handler */) = 0;
  };

class ClusterManagementIfSingletonFactory : virtual public ClusterManagementIfFactory {
 public:
  ClusterManagementIfSingletonFactory(const boost::shared_ptr<ClusterManagementIf>& iface) : iface_(iface) {}
  virtual ~ClusterManagementIfSingletonFactory() {}

  virtual ClusterManagementIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(ClusterManagementIf* /* handler */) override {}

 protected:
  boost::shared_ptr<ClusterManagementIf> iface_;
};

class ClusterManagementNull : virtual public ClusterManagementIf {
 public:
  virtual ~ClusterManagementNull() {}
  void GetServices(std::vector<ServiceInfo> & /* _return */) override {
    return;
  }
  void GetServicesByMachine(std::vector<ServiceInfo> & /* _return */, const std::string& /* machine */) override {
    return;
  }
  void GetServicesByType(std::vector<ServiceInfo> & /* _return */, const std::string& /* stype */) override {
    return;
  }
  void GetServiceById(ServiceInfo& /* _return */, const std::string& /* serviceid */) override {
    return;
  }
  int32_t ExecuteCommand(const std::string& /* serviceid */, const ServiceCommand::type /* command */, const std::string& /* arguments */) override {
    int32_t _return = 0;
    return _return;
  }
  int32_t ChangeParameters(const std::string& /* serviceid */, const std::vector<ServiceParameter> & /* parameters */, const bool /* saveinconfig */) override {
    int32_t _return = 0;
    return _return;
  }
};


class ClusterManagement_GetServices_args {
 public:

  ClusterManagement_GetServices_args(const ClusterManagement_GetServices_args&) noexcept;
  ClusterManagement_GetServices_args& operator=(const ClusterManagement_GetServices_args&) noexcept;
  ClusterManagement_GetServices_args() noexcept;

  virtual ~ClusterManagement_GetServices_args() noexcept;

  bool operator == (const ClusterManagement_GetServices_args & /* rhs */) const;
  bool operator != (const ClusterManagement_GetServices_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ClusterManagement_GetServices_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ClusterManagement_GetServices_pargs {
 public:


  virtual ~ClusterManagement_GetServices_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ClusterManagement_GetServices_result__isset {
  _ClusterManagement_GetServices_result__isset() : success(false) {}
  bool success :1;
} _ClusterManagement_GetServices_result__isset;

class ClusterManagement_GetServices_result {
 public:

  ClusterManagement_GetServices_result(const ClusterManagement_GetServices_result&);
  ClusterManagement_GetServices_result& operator=(const ClusterManagement_GetServices_result&);
  ClusterManagement_GetServices_result() noexcept;

  virtual ~ClusterManagement_GetServices_result() noexcept;
  std::vector<ServiceInfo>  success;

  _ClusterManagement_GetServices_result__isset __isset;

  void __set_success(const std::vector<ServiceInfo> & val);

  bool operator == (const ClusterManagement_GetServices_result & rhs) const;
  bool operator != (const ClusterManagement_GetServices_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ClusterManagement_GetServices_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ClusterManagement_GetServices_presult__isset {
  _ClusterManagement_GetServices_presult__isset() : success(false) {}
  bool success :1;
} _ClusterManagement_GetServices_presult__isset;

class ClusterManagement_GetServices_presult {
 public:


  virtual ~ClusterManagement_GetServices_presult() noexcept;
  std::vector<ServiceInfo> * success;

  _ClusterManagement_GetServices_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ClusterManagement_GetServicesByMachine_args__isset {
  _ClusterManagement_GetServicesByMachine_args__isset() : machine(false) {}
  bool machine :1;
} _ClusterManagement_GetServicesByMachine_args__isset;

class ClusterManagement_GetServicesByMachine_args {
 public:

  ClusterManagement_GetServicesByMachine_args(const ClusterManagement_GetServicesByMachine_args&);
  ClusterManagement_GetServicesByMachine_args& operator=(const ClusterManagement_GetServicesByMachine_args&);
  ClusterManagement_GetServicesByMachine_args() noexcept;

  virtual ~ClusterManagement_GetServicesByMachine_args() noexcept;
  std::string machine;

  _ClusterManagement_GetServicesByMachine_args__isset __isset;

  void __set_machine(const std::string& val);

  bool operator == (const ClusterManagement_GetServicesByMachine_args & rhs) const;
  bool operator != (const ClusterManagement_GetServicesByMachine_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ClusterManagement_GetServicesByMachine_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ClusterManagement_GetServicesByMachine_pargs {
 public:


  virtual ~ClusterManagement_GetServicesByMachine_pargs() noexcept;
  const std::string* machine;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ClusterManagement_GetServicesByMachine_result__isset {
  _ClusterManagement_GetServicesByMachine_result__isset() : success(false) {}
  bool success :1;
} _ClusterManagement_GetServicesByMachine_result__isset;

class ClusterManagement_GetServicesByMachine_result {
 public:

  ClusterManagement_GetServicesByMachine_result(const ClusterManagement_GetServicesByMachine_result&);
  ClusterManagement_GetServicesByMachine_result& operator=(const ClusterManagement_GetServicesByMachine_result&);
  ClusterManagement_GetServicesByMachine_result() noexcept;

  virtual ~ClusterManagement_GetServicesByMachine_result() noexcept;
  std::vector<ServiceInfo>  success;

  _ClusterManagement_GetServicesByMachine_result__isset __isset;

  void __set_success(const std::vector<ServiceInfo> & val);

  bool operator == (const ClusterManagement_GetServicesByMachine_result & rhs) const;
  bool operator != (const ClusterManagement_GetServicesByMachine_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ClusterManagement_GetServicesByMachine_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ClusterManagement_GetServicesByMachine_presult__isset {
  _ClusterManagement_GetServicesByMachine_presult__isset() : success(false) {}
  bool success :1;
} _ClusterManagement_GetServicesByMachine_presult__isset;

class ClusterManagement_GetServicesByMachine_presult {
 public:


  virtual ~ClusterManagement_GetServicesByMachine_presult() noexcept;
  std::vector<ServiceInfo> * success;

  _ClusterManagement_GetServicesByMachine_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ClusterManagement_GetServicesByType_args__isset {
  _ClusterManagement_GetServicesByType_args__isset() : stype(false) {}
  bool stype :1;
} _ClusterManagement_GetServicesByType_args__isset;

class ClusterManagement_GetServicesByType_args {
 public:

  ClusterManagement_GetServicesByType_args(const ClusterManagement_GetServicesByType_args&);
  ClusterManagement_GetServicesByType_args& operator=(const ClusterManagement_GetServicesByType_args&);
  ClusterManagement_GetServicesByType_args() noexcept;

  virtual ~ClusterManagement_GetServicesByType_args() noexcept;
  std::string stype;

  _ClusterManagement_GetServicesByType_args__isset __isset;

  void __set_stype(const std::string& val);

  bool operator == (const ClusterManagement_GetServicesByType_args & rhs) const;
  bool operator != (const ClusterManagement_GetServicesByType_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ClusterManagement_GetServicesByType_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ClusterManagement_GetServicesByType_pargs {
 public:


  virtual ~ClusterManagement_GetServicesByType_pargs() noexcept;
  const std::string* stype;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ClusterManagement_GetServicesByType_result__isset {
  _ClusterManagement_GetServicesByType_result__isset() : success(false) {}
  bool success :1;
} _ClusterManagement_GetServicesByType_result__isset;

class ClusterManagement_GetServicesByType_result {
 public:

  ClusterManagement_GetServicesByType_result(const ClusterManagement_GetServicesByType_result&);
  ClusterManagement_GetServicesByType_result& operator=(const ClusterManagement_GetServicesByType_result&);
  ClusterManagement_GetServicesByType_result() noexcept;

  virtual ~ClusterManagement_GetServicesByType_result() noexcept;
  std::vector<ServiceInfo>  success;

  _ClusterManagement_GetServicesByType_result__isset __isset;

  void __set_success(const std::vector<ServiceInfo> & val);

  bool operator == (const ClusterManagement_GetServicesByType_result & rhs) const;
  bool operator != (const ClusterManagement_GetServicesByType_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ClusterManagement_GetServicesByType_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ClusterManagement_GetServicesByType_presult__isset {
  _ClusterManagement_GetServicesByType_presult__isset() : success(false) {}
  bool success :1;
} _ClusterManagement_GetServicesByType_presult__isset;

class ClusterManagement_GetServicesByType_presult {
 public:


  virtual ~ClusterManagement_GetServicesByType_presult() noexcept;
  std::vector<ServiceInfo> * success;

  _ClusterManagement_GetServicesByType_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ClusterManagement_GetServiceById_args__isset {
  _ClusterManagement_GetServiceById_args__isset() : serviceid(false) {}
  bool serviceid :1;
} _ClusterManagement_GetServiceById_args__isset;

class ClusterManagement_GetServiceById_args {
 public:

  ClusterManagement_GetServiceById_args(const ClusterManagement_GetServiceById_args&);
  ClusterManagement_GetServiceById_args& operator=(const ClusterManagement_GetServiceById_args&);
  ClusterManagement_GetServiceById_args() noexcept;

  virtual ~ClusterManagement_GetServiceById_args() noexcept;
  std::string serviceid;

  _ClusterManagement_GetServiceById_args__isset __isset;

  void __set_serviceid(const std::string& val);

  bool operator == (const ClusterManagement_GetServiceById_args & rhs) const;
  bool operator != (const ClusterManagement_GetServiceById_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ClusterManagement_GetServiceById_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ClusterManagement_GetServiceById_pargs {
 public:


  virtual ~ClusterManagement_GetServiceById_pargs() noexcept;
  const std::string* serviceid;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ClusterManagement_GetServiceById_result__isset {
  _ClusterManagement_GetServiceById_result__isset() : success(false) {}
  bool success :1;
} _ClusterManagement_GetServiceById_result__isset;

class ClusterManagement_GetServiceById_result {
 public:

  ClusterManagement_GetServiceById_result(const ClusterManagement_GetServiceById_result&);
  ClusterManagement_GetServiceById_result& operator=(const ClusterManagement_GetServiceById_result&);
  ClusterManagement_GetServiceById_result() noexcept;

  virtual ~ClusterManagement_GetServiceById_result() noexcept;
  ServiceInfo success;

  _ClusterManagement_GetServiceById_result__isset __isset;

  void __set_success(const ServiceInfo& val);

  bool operator == (const ClusterManagement_GetServiceById_result & rhs) const;
  bool operator != (const ClusterManagement_GetServiceById_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ClusterManagement_GetServiceById_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ClusterManagement_GetServiceById_presult__isset {
  _ClusterManagement_GetServiceById_presult__isset() : success(false) {}
  bool success :1;
} _ClusterManagement_GetServiceById_presult__isset;

class ClusterManagement_GetServiceById_presult {
 public:


  virtual ~ClusterManagement_GetServiceById_presult() noexcept;
  ServiceInfo* success;

  _ClusterManagement_GetServiceById_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ClusterManagement_ExecuteCommand_args__isset {
  _ClusterManagement_ExecuteCommand_args__isset() : serviceid(false), command(false), arguments(false) {}
  bool serviceid :1;
  bool command :1;
  bool arguments :1;
} _ClusterManagement_ExecuteCommand_args__isset;

class ClusterManagement_ExecuteCommand_args {
 public:

  ClusterManagement_ExecuteCommand_args(const ClusterManagement_ExecuteCommand_args&);
  ClusterManagement_ExecuteCommand_args& operator=(const ClusterManagement_ExecuteCommand_args&);
  ClusterManagement_ExecuteCommand_args() noexcept;

  virtual ~ClusterManagement_ExecuteCommand_args() noexcept;
  std::string serviceid;
  /**
   * 
   * @see ServiceCommand
   */
  ServiceCommand::type command;
  std::string arguments;

  _ClusterManagement_ExecuteCommand_args__isset __isset;

  void __set_serviceid(const std::string& val);

  void __set_command(const ServiceCommand::type val);

  void __set_arguments(const std::string& val);

  bool operator == (const ClusterManagement_ExecuteCommand_args & rhs) const;
  bool operator != (const ClusterManagement_ExecuteCommand_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ClusterManagement_ExecuteCommand_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ClusterManagement_ExecuteCommand_pargs {
 public:


  virtual ~ClusterManagement_ExecuteCommand_pargs() noexcept;
  const std::string* serviceid;
  /**
   * 
   * @see ServiceCommand
   */
  const ServiceCommand::type* command;
  const std::string* arguments;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ClusterManagement_ExecuteCommand_result__isset {
  _ClusterManagement_ExecuteCommand_result__isset() : success(false) {}
  bool success :1;
} _ClusterManagement_ExecuteCommand_result__isset;

class ClusterManagement_ExecuteCommand_result {
 public:

  ClusterManagement_ExecuteCommand_result(const ClusterManagement_ExecuteCommand_result&) noexcept;
  ClusterManagement_ExecuteCommand_result& operator=(const ClusterManagement_ExecuteCommand_result&) noexcept;
  ClusterManagement_ExecuteCommand_result() noexcept;

  virtual ~ClusterManagement_ExecuteCommand_result() noexcept;
  int32_t success;

  _ClusterManagement_ExecuteCommand_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const ClusterManagement_ExecuteCommand_result & rhs) const;
  bool operator != (const ClusterManagement_ExecuteCommand_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ClusterManagement_ExecuteCommand_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ClusterManagement_ExecuteCommand_presult__isset {
  _ClusterManagement_ExecuteCommand_presult__isset() : success(false) {}
  bool success :1;
} _ClusterManagement_ExecuteCommand_presult__isset;

class ClusterManagement_ExecuteCommand_presult {
 public:


  virtual ~ClusterManagement_ExecuteCommand_presult() noexcept;
  int32_t* success;

  _ClusterManagement_ExecuteCommand_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ClusterManagement_ChangeParameters_args__isset {
  _ClusterManagement_ChangeParameters_args__isset() : serviceid(false), parameters(false), saveinconfig(true) {}
  bool serviceid :1;
  bool parameters :1;
  bool saveinconfig :1;
} _ClusterManagement_ChangeParameters_args__isset;

class ClusterManagement_ChangeParameters_args {
 public:

  ClusterManagement_ChangeParameters_args(const ClusterManagement_ChangeParameters_args&);
  ClusterManagement_ChangeParameters_args& operator=(const ClusterManagement_ChangeParameters_args&);
  ClusterManagement_ChangeParameters_args() noexcept;

  virtual ~ClusterManagement_ChangeParameters_args() noexcept;
  std::string serviceid;
  std::vector<ServiceParameter>  parameters;
  bool saveinconfig;

  _ClusterManagement_ChangeParameters_args__isset __isset;

  void __set_serviceid(const std::string& val);

  void __set_parameters(const std::vector<ServiceParameter> & val);

  void __set_saveinconfig(const bool val);

  bool operator == (const ClusterManagement_ChangeParameters_args & rhs) const;
  bool operator != (const ClusterManagement_ChangeParameters_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ClusterManagement_ChangeParameters_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ClusterManagement_ChangeParameters_pargs {
 public:


  virtual ~ClusterManagement_ChangeParameters_pargs() noexcept;
  const std::string* serviceid;
  const std::vector<ServiceParameter> * parameters;
  const bool* saveinconfig;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ClusterManagement_ChangeParameters_result__isset {
  _ClusterManagement_ChangeParameters_result__isset() : success(false) {}
  bool success :1;
} _ClusterManagement_ChangeParameters_result__isset;

class ClusterManagement_ChangeParameters_result {
 public:

  ClusterManagement_ChangeParameters_result(const ClusterManagement_ChangeParameters_result&) noexcept;
  ClusterManagement_ChangeParameters_result& operator=(const ClusterManagement_ChangeParameters_result&) noexcept;
  ClusterManagement_ChangeParameters_result() noexcept;

  virtual ~ClusterManagement_ChangeParameters_result() noexcept;
  int32_t success;

  _ClusterManagement_ChangeParameters_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const ClusterManagement_ChangeParameters_result & rhs) const;
  bool operator != (const ClusterManagement_ChangeParameters_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ClusterManagement_ChangeParameters_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ClusterManagement_ChangeParameters_presult__isset {
  _ClusterManagement_ChangeParameters_presult__isset() : success(false) {}
  bool success :1;
} _ClusterManagement_ChangeParameters_presult__isset;

class ClusterManagement_ChangeParameters_presult {
 public:


  virtual ~ClusterManagement_ChangeParameters_presult() noexcept;
  int32_t* success;

  _ClusterManagement_ChangeParameters_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ClusterManagementClient : virtual public ClusterManagementIf {
 public:
  ClusterManagementClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ClusterManagementClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void GetServices(std::vector<ServiceInfo> & _return) override;
  void send_GetServices();
  void recv_GetServices(std::vector<ServiceInfo> & _return);
  void GetServicesByMachine(std::vector<ServiceInfo> & _return, const std::string& machine) override;
  void send_GetServicesByMachine(const std::string& machine);
  void recv_GetServicesByMachine(std::vector<ServiceInfo> & _return);
  void GetServicesByType(std::vector<ServiceInfo> & _return, const std::string& stype) override;
  void send_GetServicesByType(const std::string& stype);
  void recv_GetServicesByType(std::vector<ServiceInfo> & _return);
  void GetServiceById(ServiceInfo& _return, const std::string& serviceid) override;
  void send_GetServiceById(const std::string& serviceid);
  void recv_GetServiceById(ServiceInfo& _return);
  int32_t ExecuteCommand(const std::string& serviceid, const ServiceCommand::type command, const std::string& arguments) override;
  void send_ExecuteCommand(const std::string& serviceid, const ServiceCommand::type command, const std::string& arguments);
  int32_t recv_ExecuteCommand();
  int32_t ChangeParameters(const std::string& serviceid, const std::vector<ServiceParameter> & parameters, const bool saveinconfig) override;
  void send_ChangeParameters(const std::string& serviceid, const std::vector<ServiceParameter> & parameters, const bool saveinconfig);
  int32_t recv_ChangeParameters();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ClusterManagementProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ClusterManagementIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (ClusterManagementProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_GetServices(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_GetServicesByMachine(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_GetServicesByType(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_GetServiceById(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ExecuteCommand(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ChangeParameters(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ClusterManagementProcessor(boost::shared_ptr<ClusterManagementIf> iface) :
    iface_(iface) {
    processMap_["GetServices"] = &ClusterManagementProcessor::process_GetServices;
    processMap_["GetServicesByMachine"] = &ClusterManagementProcessor::process_GetServicesByMachine;
    processMap_["GetServicesByType"] = &ClusterManagementProcessor::process_GetServicesByType;
    processMap_["GetServiceById"] = &ClusterManagementProcessor::process_GetServiceById;
    processMap_["ExecuteCommand"] = &ClusterManagementProcessor::process_ExecuteCommand;
    processMap_["ChangeParameters"] = &ClusterManagementProcessor::process_ChangeParameters;
  }

  virtual ~ClusterManagementProcessor() {}
};

class ClusterManagementProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ClusterManagementProcessorFactory(const ::std::shared_ptr< ClusterManagementIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< ClusterManagementIfFactory > handlerFactory_;
};

class ClusterManagementMultiface : virtual public ClusterManagementIf {
 public:
  ClusterManagementMultiface(std::vector<std::shared_ptr<ClusterManagementIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ClusterManagementMultiface() {}
 protected:
  std::vector<std::shared_ptr<ClusterManagementIf> > ifaces_;
  ClusterManagementMultiface() {}
  void add(boost::shared_ptr<ClusterManagementIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void GetServices(std::vector<ServiceInfo> & _return) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetServices(_return);
    }
    ifaces_[i]->GetServices(_return);
    return;
  }

  void GetServicesByMachine(std::vector<ServiceInfo> & _return, const std::string& machine) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetServicesByMachine(_return, machine);
    }
    ifaces_[i]->GetServicesByMachine(_return, machine);
    return;
  }

  void GetServicesByType(std::vector<ServiceInfo> & _return, const std::string& stype) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetServicesByType(_return, stype);
    }
    ifaces_[i]->GetServicesByType(_return, stype);
    return;
  }

  void GetServiceById(ServiceInfo& _return, const std::string& serviceid) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetServiceById(_return, serviceid);
    }
    ifaces_[i]->GetServiceById(_return, serviceid);
    return;
  }

  int32_t ExecuteCommand(const std::string& serviceid, const ServiceCommand::type command, const std::string& arguments) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ExecuteCommand(serviceid, command, arguments);
    }
    return ifaces_[i]->ExecuteCommand(serviceid, command, arguments);
  }

  int32_t ChangeParameters(const std::string& serviceid, const std::vector<ServiceParameter> & parameters, const bool saveinconfig) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ChangeParameters(serviceid, parameters, saveinconfig);
    }
    return ifaces_[i]->ChangeParameters(serviceid, parameters, saveinconfig);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ClusterManagementConcurrentClient : virtual public ClusterManagementIf {
 public:
  ClusterManagementConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  ClusterManagementConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void GetServices(std::vector<ServiceInfo> & _return) override;
  int32_t send_GetServices();
  void recv_GetServices(std::vector<ServiceInfo> & _return, const int32_t seqid);
  void GetServicesByMachine(std::vector<ServiceInfo> & _return, const std::string& machine) override;
  int32_t send_GetServicesByMachine(const std::string& machine);
  void recv_GetServicesByMachine(std::vector<ServiceInfo> & _return, const int32_t seqid);
  void GetServicesByType(std::vector<ServiceInfo> & _return, const std::string& stype) override;
  int32_t send_GetServicesByType(const std::string& stype);
  void recv_GetServicesByType(std::vector<ServiceInfo> & _return, const int32_t seqid);
  void GetServiceById(ServiceInfo& _return, const std::string& serviceid) override;
  int32_t send_GetServiceById(const std::string& serviceid);
  void recv_GetServiceById(ServiceInfo& _return, const int32_t seqid);
  int32_t ExecuteCommand(const std::string& serviceid, const ServiceCommand::type command, const std::string& arguments) override;
  int32_t send_ExecuteCommand(const std::string& serviceid, const ServiceCommand::type command, const std::string& arguments);
  int32_t recv_ExecuteCommand(const int32_t seqid);
  int32_t ChangeParameters(const std::string& serviceid, const std::vector<ServiceParameter> & parameters, const bool saveinconfig) override;
  int32_t send_ChangeParameters(const std::string& serviceid, const std::vector<ServiceParameter> & parameters, const bool saveinconfig);
  int32_t recv_ChangeParameters(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}} // namespace

#endif
