/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ClusterManagementAPI_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace ClusterAdmin { namespace Thrift {

int _kServiceStatusValues[] = {
  ServiceStatus::RUNNING,
  ServiceStatus::STOPPED,
  ServiceStatus::START_PENDING,
  ServiceStatus::STOP_PENDING,
  ServiceStatus::WAITING_FOR_STOP,
  ServiceStatus::WAITING_FOR_RESTART
};
const char* _kServiceStatusNames[] = {
  "RUNNING",
  "STOPPED",
  "START_PENDING",
  "STOP_PENDING",
  "WAITING_FOR_STOP",
  "WAITING_FOR_RESTART"
};
const std::map<int, const char*> _ServiceStatus_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(6, _kServiceStatusValues, _kServiceStatusNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const ServiceStatus::type& val) {
  std::map<int, const char*>::const_iterator it = _ServiceStatus_VALUES_TO_NAMES.find(val);
  if (it != _ServiceStatus_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const ServiceStatus::type& val) {
  std::map<int, const char*>::const_iterator it = _ServiceStatus_VALUES_TO_NAMES.find(val);
  if (it != _ServiceStatus_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kServiceCommandValues[] = {
  ServiceCommand::START,
  ServiceCommand::STOP,
  ServiceCommand::RESTART,
  ServiceCommand::SOFT_STOP,
  ServiceCommand::SOFT_RESTART,
  ServiceCommand::RELOAD_CONFIG
};
const char* _kServiceCommandNames[] = {
  "START",
  "STOP",
  "RESTART",
  "SOFT_STOP",
  "SOFT_RESTART",
  "RELOAD_CONFIG"
};
const std::map<int, const char*> _ServiceCommand_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(6, _kServiceCommandValues, _kServiceCommandNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const ServiceCommand::type& val) {
  std::map<int, const char*>::const_iterator it = _ServiceCommand_VALUES_TO_NAMES.find(val);
  if (it != _ServiceCommand_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const ServiceCommand::type& val) {
  std::map<int, const char*>::const_iterator it = _ServiceCommand_VALUES_TO_NAMES.find(val);
  if (it != _ServiceCommand_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


ServiceParameter::~ServiceParameter() noexcept {
}

ServiceParameter::ServiceParameter() noexcept
   : name(),
     value(),
     changeable(0),
     needrestart(0) {
}

void ServiceParameter::__set_name(const std::string& val) {
  this->name = val;
}

void ServiceParameter::__set_value(const std::string& val) {
  this->value = val;
}

void ServiceParameter::__set_changeable(const bool val) {
  this->changeable = val;
}

void ServiceParameter::__set_needrestart(const bool val) {
  this->needrestart = val;
}
std::ostream& operator<<(std::ostream& out, const ServiceParameter& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ServiceParameter::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->value);
          this->__isset.value = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->changeable);
          this->__isset.changeable = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->needrestart);
          this->__isset.needrestart = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ServiceParameter::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ServiceParameter");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("value", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->value);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("changeable", ::apache::thrift::protocol::T_BOOL, 3);
  xfer += oprot->writeBool(this->changeable);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("needrestart", ::apache::thrift::protocol::T_BOOL, 4);
  xfer += oprot->writeBool(this->needrestart);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ServiceParameter &a, ServiceParameter &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.value, b.value);
  swap(a.changeable, b.changeable);
  swap(a.needrestart, b.needrestart);
  swap(a.__isset, b.__isset);
}

bool ServiceParameter::operator==(const ServiceParameter & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(value == rhs.value))
    return false;
  if (!(changeable == rhs.changeable))
    return false;
  if (!(needrestart == rhs.needrestart))
    return false;
  return true;
}

ServiceParameter::ServiceParameter(const ServiceParameter& other0) {
  name = other0.name;
  value = other0.value;
  changeable = other0.changeable;
  needrestart = other0.needrestart;
  __isset = other0.__isset;
}
ServiceParameter& ServiceParameter::operator=(const ServiceParameter& other1) {
  name = other1.name;
  value = other1.value;
  changeable = other1.changeable;
  needrestart = other1.needrestart;
  __isset = other1.__isset;
  return *this;
}
void ServiceParameter::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ServiceParameter(";
  out << "name=" << to_string(name);
  out << ", " << "value=" << to_string(value);
  out << ", " << "changeable=" << to_string(changeable);
  out << ", " << "needrestart=" << to_string(needrestart);
  out << ")";
}


ServiceInfo::~ServiceInfo() noexcept {
}

ServiceInfo::ServiceInfo() noexcept
   : sid(),
     stype(),
     machine(),
     status(static_cast<ServiceStatus::type>(0)),
     pid(0),
     uptime(0),
     backendaddr(),
     frontendaddr() {
}

void ServiceInfo::__set_sid(const std::string& val) {
  this->sid = val;
}

void ServiceInfo::__set_stype(const std::string& val) {
  this->stype = val;
}

void ServiceInfo::__set_machine(const std::string& val) {
  this->machine = val;
}

void ServiceInfo::__set_status(const ServiceStatus::type val) {
  this->status = val;
}

void ServiceInfo::__set_pid(const int32_t val) {
  this->pid = val;
}

void ServiceInfo::__set_uptime(const int32_t val) {
  this->uptime = val;
}

void ServiceInfo::__set_backendaddr(const std::string& val) {
  this->backendaddr = val;
}

void ServiceInfo::__set_frontendaddr(const std::string& val) {
  this->frontendaddr = val;
}

void ServiceInfo::__set_parameters(const std::vector<ServiceParameter> & val) {
  this->parameters = val;
}
std::ostream& operator<<(std::ostream& out, const ServiceInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ServiceInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->sid);
          this->__isset.sid = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->stype);
          this->__isset.stype = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->machine);
          this->__isset.machine = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast2;
          xfer += iprot->readI32(ecast2);
          this->status = static_cast<ServiceStatus::type>(ecast2);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->pid);
          this->__isset.pid = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->uptime);
          this->__isset.uptime = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->backendaddr);
          this->__isset.backendaddr = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->frontendaddr);
          this->__isset.frontendaddr = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->parameters.clear();
            uint32_t _size3;
            ::apache::thrift::protocol::TType _etype6;
            xfer += iprot->readListBegin(_etype6, _size3);
            this->parameters.resize(_size3);
            uint32_t _i7;
            for (_i7 = 0; _i7 < _size3; ++_i7)
            {
              xfer += this->parameters[_i7].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.parameters = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ServiceInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ServiceInfo");

  xfer += oprot->writeFieldBegin("sid", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->sid);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("stype", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->stype);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("machine", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->machine);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 4);
  xfer += oprot->writeI32(static_cast<int32_t>(this->status));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pid", ::apache::thrift::protocol::T_I32, 5);
  xfer += oprot->writeI32(this->pid);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("uptime", ::apache::thrift::protocol::T_I32, 6);
  xfer += oprot->writeI32(this->uptime);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("backendaddr", ::apache::thrift::protocol::T_STRING, 7);
  xfer += oprot->writeString(this->backendaddr);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("frontendaddr", ::apache::thrift::protocol::T_STRING, 8);
  xfer += oprot->writeString(this->frontendaddr);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("parameters", ::apache::thrift::protocol::T_LIST, 9);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->parameters.size()));
    std::vector<ServiceParameter> ::const_iterator _iter8;
    for (_iter8 = this->parameters.begin(); _iter8 != this->parameters.end(); ++_iter8)
    {
      xfer += (*_iter8).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ServiceInfo &a, ServiceInfo &b) {
  using ::std::swap;
  swap(a.sid, b.sid);
  swap(a.stype, b.stype);
  swap(a.machine, b.machine);
  swap(a.status, b.status);
  swap(a.pid, b.pid);
  swap(a.uptime, b.uptime);
  swap(a.backendaddr, b.backendaddr);
  swap(a.frontendaddr, b.frontendaddr);
  swap(a.parameters, b.parameters);
  swap(a.__isset, b.__isset);
}

bool ServiceInfo::operator==(const ServiceInfo & rhs) const
{
  if (!(sid == rhs.sid))
    return false;
  if (!(stype == rhs.stype))
    return false;
  if (!(machine == rhs.machine))
    return false;
  if (!(status == rhs.status))
    return false;
  if (!(pid == rhs.pid))
    return false;
  if (!(uptime == rhs.uptime))
    return false;
  if (!(backendaddr == rhs.backendaddr))
    return false;
  if (!(frontendaddr == rhs.frontendaddr))
    return false;
  if (!(parameters == rhs.parameters))
    return false;
  return true;
}

ServiceInfo::ServiceInfo(const ServiceInfo& other9) {
  sid = other9.sid;
  stype = other9.stype;
  machine = other9.machine;
  status = other9.status;
  pid = other9.pid;
  uptime = other9.uptime;
  backendaddr = other9.backendaddr;
  frontendaddr = other9.frontendaddr;
  parameters = other9.parameters;
  __isset = other9.__isset;
}
ServiceInfo& ServiceInfo::operator=(const ServiceInfo& other10) {
  sid = other10.sid;
  stype = other10.stype;
  machine = other10.machine;
  status = other10.status;
  pid = other10.pid;
  uptime = other10.uptime;
  backendaddr = other10.backendaddr;
  frontendaddr = other10.frontendaddr;
  parameters = other10.parameters;
  __isset = other10.__isset;
  return *this;
}
void ServiceInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ServiceInfo(";
  out << "sid=" << to_string(sid);
  out << ", " << "stype=" << to_string(stype);
  out << ", " << "machine=" << to_string(machine);
  out << ", " << "status=" << to_string(status);
  out << ", " << "pid=" << to_string(pid);
  out << ", " << "uptime=" << to_string(uptime);
  out << ", " << "backendaddr=" << to_string(backendaddr);
  out << ", " << "frontendaddr=" << to_string(frontendaddr);
  out << ", " << "parameters=" << to_string(parameters);
  out << ")";
}

}} // namespace
