/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ClusterManagementAPI_TYPES_H
#define ClusterManagementAPI_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace ClusterAdmin { namespace Thrift {

struct ServiceStatus {
  enum type {
    RUNNING = 1,
    STOPPED = 2,
    START_PENDING = 3,
    STOP_PENDING = 4,
    WAITING_FOR_STOP = 5,
    WAITING_FOR_RESTART = 6
  };
};

extern const std::map<int, const char*> _ServiceStatus_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const ServiceStatus::type& val);

std::string to_string(const ServiceStatus::type& val);

struct ServiceCommand {
  enum type {
    START = 1,
    STOP = 2,
    RESTART = 4,
    SOFT_STOP = 8,
    SOFT_RESTART = 16,
    RELOAD_CONFIG = 32
  };
};

extern const std::map<int, const char*> _ServiceCommand_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const ServiceCommand::type& val);

std::string to_string(const ServiceCommand::type& val);

class ServiceParameter;

class ServiceInfo;

typedef struct _ServiceParameter__isset {
  _ServiceParameter__isset() : name(false), value(false), changeable(false), needrestart(false) {}
  bool name :1;
  bool value :1;
  bool changeable :1;
  bool needrestart :1;
} _ServiceParameter__isset;

class ServiceParameter : public virtual ::apache::thrift::TBase {
 public:

  ServiceParameter(const ServiceParameter&);
  ServiceParameter& operator=(const ServiceParameter&);
  ServiceParameter() noexcept;

  virtual ~ServiceParameter() noexcept;
  std::string name;
  std::string value;
  bool changeable;
  bool needrestart;

  _ServiceParameter__isset __isset;

  void __set_name(const std::string& val);

  void __set_value(const std::string& val);

  void __set_changeable(const bool val);

  void __set_needrestart(const bool val);

  bool operator == (const ServiceParameter & rhs) const;
  bool operator != (const ServiceParameter &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ServiceParameter & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ServiceParameter &a, ServiceParameter &b);

std::ostream& operator<<(std::ostream& out, const ServiceParameter& obj);

typedef struct _ServiceInfo__isset {
  _ServiceInfo__isset() : sid(false), stype(false), machine(false), status(false), pid(false), uptime(false), backendaddr(false), frontendaddr(false), parameters(false) {}
  bool sid :1;
  bool stype :1;
  bool machine :1;
  bool status :1;
  bool pid :1;
  bool uptime :1;
  bool backendaddr :1;
  bool frontendaddr :1;
  bool parameters :1;
} _ServiceInfo__isset;

class ServiceInfo : public virtual ::apache::thrift::TBase {
 public:

  ServiceInfo(const ServiceInfo&);
  ServiceInfo& operator=(const ServiceInfo&);
  ServiceInfo() noexcept;

  virtual ~ServiceInfo() noexcept;
  std::string sid;
  std::string stype;
  std::string machine;
  /**
   * 
   * @see ServiceStatus
   */
  ServiceStatus::type status;
  int32_t pid;
  int32_t uptime;
  std::string backendaddr;
  std::string frontendaddr;
  std::vector<ServiceParameter>  parameters;

  _ServiceInfo__isset __isset;

  void __set_sid(const std::string& val);

  void __set_stype(const std::string& val);

  void __set_machine(const std::string& val);

  void __set_status(const ServiceStatus::type val);

  void __set_pid(const int32_t val);

  void __set_uptime(const int32_t val);

  void __set_backendaddr(const std::string& val);

  void __set_frontendaddr(const std::string& val);

  void __set_parameters(const std::vector<ServiceParameter> & val);

  bool operator == (const ServiceInfo & rhs) const;
  bool operator != (const ServiceInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ServiceInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ServiceInfo &a, ServiceInfo &b);

std::ostream& operator<<(std::ostream& out, const ServiceInfo& obj);

}} // namespace

#endif
