/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Monitoring_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace Monitoring { namespace Thrift {

int _kPerfCounterTypeValues[] = {
  PerfCounterType::Bool,
  PerfCounterType::Byte,
  PerfCounterType::Int16,
  PerfCounterType::UInt16,
  PerfCounterType::Int32,
  PerfCounterType::UInt32,
  PerfCounterType::Int64,
  PerfCounterType::UInt64,
  PerfCounterType::Float,
  PerfCounterType::Double,
  PerfCounterType::String
};
const char* _kPerfCounterTypeNames[] = {
  "Bool",
  "Byte",
  "Int16",
  "UInt16",
  "Int32",
  "UInt32",
  "Int64",
  "UInt64",
  "Float",
  "Double",
  "String"
};
const std::map<int, const char*> _PerfCounterType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(11, _kPerfCounterTypeValues, _kPerfCounterTypeNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const PerfCounterType::type& val) {
  std::map<int, const char*>::const_iterator it = _PerfCounterType_VALUES_TO_NAMES.find(val);
  if (it != _PerfCounterType_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const PerfCounterType::type& val) {
  std::map<int, const char*>::const_iterator it = _PerfCounterType_VALUES_TO_NAMES.find(val);
  if (it != _PerfCounterType_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


PerfCounterInfo::~PerfCounterInfo() noexcept {
}

PerfCounterInfo::PerfCounterInfo() noexcept
   : name(),
     period(0) {
}

void PerfCounterInfo::__set_name(const std::string& val) {
  this->name = val;
}

void PerfCounterInfo::__set_period(const int32_t val) {
  this->period = val;
}
std::ostream& operator<<(std::ostream& out, const PerfCounterInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t PerfCounterInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->period);
          this->__isset.period = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t PerfCounterInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("PerfCounterInfo");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("period", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->period);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(PerfCounterInfo &a, PerfCounterInfo &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.period, b.period);
  swap(a.__isset, b.__isset);
}

bool PerfCounterInfo::operator==(const PerfCounterInfo & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(period == rhs.period))
    return false;
  return true;
}

PerfCounterInfo::PerfCounterInfo(const PerfCounterInfo& other0) {
  name = other0.name;
  period = other0.period;
  __isset = other0.__isset;
}
PerfCounterInfo& PerfCounterInfo::operator=(const PerfCounterInfo& other1) {
  name = other1.name;
  period = other1.period;
  __isset = other1.__isset;
  return *this;
}
void PerfCounterInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "PerfCounterInfo(";
  out << "name=" << to_string(name);
  out << ", " << "period=" << to_string(period);
  out << ")";
}


PerfCounterSample::~PerfCounterSample() noexcept {
}

PerfCounterSample::PerfCounterSample() noexcept
   : name(),
     type(static_cast<PerfCounterType::type>(0)),
     value(),
     timestamp(0) {
}

void PerfCounterSample::__set_name(const std::string& val) {
  this->name = val;
}

void PerfCounterSample::__set_type(const PerfCounterType::type val) {
  this->type = val;
}

void PerfCounterSample::__set_value(const std::string& val) {
  this->value = val;
}

void PerfCounterSample::__set_timestamp(const int32_t val) {
  this->timestamp = val;
}
std::ostream& operator<<(std::ostream& out, const PerfCounterSample& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t PerfCounterSample::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast2;
          xfer += iprot->readI32(ecast2);
          this->type = static_cast<PerfCounterType::type>(ecast2);
          this->__isset.type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->value);
          this->__isset.value = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->timestamp);
          this->__isset.timestamp = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t PerfCounterSample::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("PerfCounterSample");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(static_cast<int32_t>(this->type));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("value", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->value);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("timestamp", ::apache::thrift::protocol::T_I32, 4);
  xfer += oprot->writeI32(this->timestamp);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(PerfCounterSample &a, PerfCounterSample &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.type, b.type);
  swap(a.value, b.value);
  swap(a.timestamp, b.timestamp);
  swap(a.__isset, b.__isset);
}

bool PerfCounterSample::operator==(const PerfCounterSample & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(type == rhs.type))
    return false;
  if (!(value == rhs.value))
    return false;
  if (!(timestamp == rhs.timestamp))
    return false;
  return true;
}

PerfCounterSample::PerfCounterSample(const PerfCounterSample& other3) {
  name = other3.name;
  type = other3.type;
  value = other3.value;
  timestamp = other3.timestamp;
  __isset = other3.__isset;
}
PerfCounterSample& PerfCounterSample::operator=(const PerfCounterSample& other4) {
  name = other4.name;
  type = other4.type;
  value = other4.value;
  timestamp = other4.timestamp;
  __isset = other4.__isset;
  return *this;
}
void PerfCounterSample::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "PerfCounterSample(";
  out << "name=" << to_string(name);
  out << ", " << "type=" << to_string(type);
  out << ", " << "value=" << to_string(value);
  out << ", " << "timestamp=" << to_string(timestamp);
  out << ")";
}

}} // namespace
