/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Monitoring_TYPES_H
#define Monitoring_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace Monitoring { namespace Thrift {

struct PerfCounterType {
  enum type {
    Bool = 1,
    Byte = 2,
    Int16 = 3,
    UInt16 = 4,
    Int32 = 5,
    UInt32 = 6,
    Int64 = 7,
    UInt64 = 8,
    Float = 9,
    Double = 10,
    String = 11
  };
};

extern const std::map<int, const char*> _PerfCounterType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const PerfCounterType::type& val);

std::string to_string(const PerfCounterType::type& val);

class PerfCounterInfo;

class PerfCounterSample;

typedef struct _PerfCounterInfo__isset {
  _PerfCounterInfo__isset() : name(false), period(false) {}
  bool name :1;
  bool period :1;
} _PerfCounterInfo__isset;

class PerfCounterInfo : public virtual ::apache::thrift::TBase {
 public:

  PerfCounterInfo(const PerfCounterInfo&);
  PerfCounterInfo& operator=(const PerfCounterInfo&);
  PerfCounterInfo() noexcept;

  virtual ~PerfCounterInfo() noexcept;
  std::string name;
  int32_t period;

  _PerfCounterInfo__isset __isset;

  void __set_name(const std::string& val);

  void __set_period(const int32_t val);

  bool operator == (const PerfCounterInfo & rhs) const;
  bool operator != (const PerfCounterInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PerfCounterInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(PerfCounterInfo &a, PerfCounterInfo &b);

std::ostream& operator<<(std::ostream& out, const PerfCounterInfo& obj);

typedef struct _PerfCounterSample__isset {
  _PerfCounterSample__isset() : name(false), type(false), value(false), timestamp(false) {}
  bool name :1;
  bool type :1;
  bool value :1;
  bool timestamp :1;
} _PerfCounterSample__isset;

class PerfCounterSample : public virtual ::apache::thrift::TBase {
 public:

  PerfCounterSample(const PerfCounterSample&);
  PerfCounterSample& operator=(const PerfCounterSample&);
  PerfCounterSample() noexcept;

  virtual ~PerfCounterSample() noexcept;
  std::string name;
  /**
   * 
   * @see PerfCounterType
   */
  PerfCounterType::type type;
  std::string value;
  int32_t timestamp;

  _PerfCounterSample__isset __isset;

  void __set_name(const std::string& val);

  void __set_type(const PerfCounterType::type val);

  void __set_value(const std::string& val);

  void __set_timestamp(const int32_t val);

  bool operator == (const PerfCounterSample & rhs) const;
  bool operator != (const PerfCounterSample &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PerfCounterSample & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(PerfCounterSample &a, PerfCounterSample &b);

std::ostream& operator<<(std::ostream& out, const PerfCounterSample& obj);

}} // namespace

#endif
