#pragma once
// The platform is selected by NV_LINUX_PLATFORM (defined only in the Linux build);
// everything else is treated as Windows: WIN32 / NV_WIN_PLATFORM are not visible
// to every project in this solution.

// ============================================================================
// Web skin index -> skin persistent id (moved verbatim out of
// PF_GameLogic/WebLauncher.cpp:GetSkinByHeroPersistentId).
//
// The order of the lists defines the meaning of the index the back-end sends as
// usersData[].skin, so it MUST NOT be re-sorted. Resolution happens on the
// server (Shared/WebSessionParse.h) and the resulting skin persistent id string
// travels to the clients in NCore::PlayerInfo::heroSkin.
// ============================================================================

#include <string>
#include <vector>
#include <map>

namespace WebSession
{
inline std::string ResolveSkin(const std::string& heroPersistentId, int skinId)
{
  const char* heroes [] = {
    "prince",
    "snowqueen",
    "faceless",
    "warlord",
    "thundergod",
    "invisible",
    "mowgly",
    "inventor",
    "artist",
    "highlander",
    "marine",
    "firefox",
    "healer",
    "night",
    "rockman",
    "assassin",
    "unicorn",
    "hunter",
    "ghostlord",
    "ratcatcher",
    "archeress",
    "werewolf",
    "frogenglut",
    "witchdoctor",
    "manawyrm",
    "bard",
    "naga",
    "mage",
    "fairy",
    "witcher",
    "alchemist",
    "demonolog",
    "vampire",
    "witch",
    "crusader_A",
    "crusader_B",
    "monster",
    "angel",
    "freeze",
    "gunslinger",
    "reaper",
    "fluffy",
    "rifleman",
    "magicgirl",
    "pinkgirl",
    "ironknight",
    "fallenangel",
    "bladedancer",
    "ent",
    "plaguedoctor",
    "katana",
    "plane",
    "zealot",
    "wraithking",
    "dryad",
    "stalker",
    "gunner",
    "chronicle",
    "brewer",
    "shadow",
    "wendigo",
    "trickster",
    "banshee",
    "shaman",
    "bomber"
  };

  int heroId = 0;
  for (int i = 0; i < (int)(sizeof(heroes)/sizeof(heroes[0])); ++i) {
    if (heroPersistentId == heroes[i]) {
      heroId = i + 1;
      break;
    }
  }

  std::map<int, std::vector<std::string>> skinMap;

  skinMap[1].push_back("prince_S0_A");
  skinMap[1].push_back("prince_S1_A");
  skinMap[1].push_back("prince_S2_A");
  skinMap[1].push_back("prince_S4");
  skinMap[1].push_back("prince_S5");
  skinMap[1].push_back("prince_S0_B");
  skinMap[1].push_back("prince_S1_B");
  skinMap[1].push_back("prince_S2_B");
  skinMap[1].push_back("prince_S3");
  skinMap[2].push_back("snowqueen_S0_A");
  skinMap[2].push_back("snowqueen_S1_A");
  skinMap[2].push_back("snowqueen_S2_A");
  skinMap[2].push_back("snowqueen_S4");
  skinMap[2].push_back("snowqueen_S5");
  skinMap[2].push_back("snowqueen_S0_B");
  skinMap[2].push_back("snowqueen_S1_B");
  skinMap[2].push_back("snowqueen_S2_B");
  skinMap[2].push_back("snowqueen_S6");
  skinMap[2].push_back("snowqueen_S7");
  skinMap[3].push_back("faceless_S0_A");
  skinMap[3].push_back("faceless_S1_A");
  skinMap[3].push_back("faceless_S2_A");
  skinMap[3].push_back("faceless_S0_B");
  skinMap[3].push_back("faceless_S1_B");
  skinMap[3].push_back("faceless_S2_B");
  skinMap[3].push_back("faceless_S3");
  skinMap[4].push_back("warlord_S0_A");
  skinMap[4].push_back("warlord_S3");
  skinMap[4].push_back("warlord_S0_B");
  skinMap[4].push_back("warlord_S1_B");
  skinMap[4].push_back("warlord_S2");
  skinMap[4].push_back("warlord_S1_A");
  skinMap[5].push_back("thundergod_S0_A");
  skinMap[5].push_back("thundergod_S0_B");
  skinMap[5].push_back("thundergod_S1_B");
  skinMap[5].push_back("thundergod_S2_B");
  skinMap[5].push_back("thundergod_S4");
  skinMap[5].push_back("thundergod_S5");
  skinMap[5].push_back("thundergod_S6");
  skinMap[5].push_back("thundergod_S1_A");
  skinMap[5].push_back("thundergod_S2_A");
  skinMap[6].push_back("invisible_S0_A");
  skinMap[6].push_back("invisible_S1_B");
  skinMap[6].push_back("invisible_S2");
  skinMap[6].push_back("invisible_S4");
  skinMap[6].push_back("invisible_S1_A");
  skinMap[6].push_back("invisible_S0_B");
  skinMap[7].push_back("mowgly_S0_A");
  skinMap[7].push_back("mowgly_S0_B");
  skinMap[7].push_back("mowgly_S1_B");
  skinMap[7].push_back("mowgly_S2_B");
  skinMap[7].push_back("mowgly_S2_A");
  skinMap[7].push_back("mowgly_S1_A");
  skinMap[8].push_back("inventor");
  skinMap[8].push_back("inventor_S3");
  skinMap[8].push_back("inventor_S2");
  skinMap[8].push_back("inventor_S1");
  skinMap[9].push_back("artist");
  skinMap[9].push_back("artist_S3");
  skinMap[9].push_back("artist_S1");
  skinMap[9].push_back("artist_S2");
  skinMap[9].push_back("artist_S4");
  skinMap[10].push_back("highlander_S0_A");
  skinMap[10].push_back("highlander_S3_B");
  skinMap[10].push_back("highlander_S4");
  skinMap[10].push_back("highlander_S1_A");
  skinMap[10].push_back("highlander_S2_B");
  skinMap[10].push_back("highlander_S3_A");
  skinMap[10].push_back("highlander_S0_B");
  skinMap[10].push_back("highlander_S1_B");
  skinMap[10].push_back("highlander_S2_A");
  skinMap[11].push_back("marine_S0_A");
  skinMap[11].push_back("marine_S1_B");
  skinMap[11].push_back("marine_S2_B");
  skinMap[11].push_back("marine_S3_B");
  skinMap[11].push_back("marine_S4");
  skinMap[11].push_back("marine_S5");
  skinMap[11].push_back("marine_S1_A");
  skinMap[11].push_back("marine_S2_A");
  skinMap[11].push_back("marine_S0_B");
  skinMap[11].push_back("marine_S3_A");
  skinMap[12].push_back("firefox_S0_A");
  skinMap[12].push_back("firefox_S1_A");
  skinMap[12].push_back("firefox_S2_A");
  skinMap[12].push_back("firefox_S3");
  skinMap[12].push_back("firefox_S4_A");
  skinMap[12].push_back("firefox_S0_B");
  skinMap[12].push_back("firefox_S1_B");
  skinMap[12].push_back("firefox_S2_B");
  skinMap[12].push_back("firefox_S4_B");
  skinMap[12].push_back("firefox_S5");
  skinMap[13].push_back("healer_S0_A");
  skinMap[13].push_back("healer_S3_A");
  skinMap[13].push_back("healer_S4_A");
  skinMap[13].push_back("healer_S0_B");
  skinMap[13].push_back("healer_S1_B");
  skinMap[13].push_back("healer_S3_B");
  skinMap[13].push_back("healer_S4_B");
  skinMap[13].push_back("healer_S1_A");
  skinMap[13].push_back("healer_S2");
  skinMap[14].push_back("night_S0_A");
  skinMap[14].push_back("night_S3_A");
  skinMap[14].push_back("night_S4");
  skinMap[14].push_back("night_S1_B");
  skinMap[14].push_back("night_S0_B");
  skinMap[14].push_back("night_S2_B");
  skinMap[14].push_back("night_S5");
  skinMap[14].push_back("night_S1_A");
  skinMap[14].push_back("night_S2_A");
  skinMap[14].push_back("night_S3_B");
  skinMap[15].push_back("rockman_S0_A");
  skinMap[15].push_back("rockman_S2_A");
  skinMap[15].push_back("rockman_S0_B");
  skinMap[15].push_back("rockman_S1_B");
  skinMap[15].push_back("rockman_S2_B");
  skinMap[15].push_back("rockman_S3");
  skinMap[15].push_back("rockman_S1_A");
  skinMap[16].push_back("assassin_S0_A");
  skinMap[16].push_back("assassin_S1_B");
  skinMap[16].push_back("assassin_S3");
  skinMap[16].push_back("assassin_S4");
  skinMap[16].push_back("assassin_S1_A");
  skinMap[16].push_back("assassin_S2");
  skinMap[16].push_back("assassin_S0_B");
  skinMap[16].push_back("assassin_S5");
  skinMap[16].push_back("assassin_S6");
  skinMap[17].push_back("unicorn_S0_A");
  skinMap[17].push_back("unicorn_S3");
  skinMap[17].push_back("unicorn_S0_B");
  skinMap[17].push_back("unicorn_S1_B");
  skinMap[17].push_back("unicorn_S1_A");
  skinMap[18].push_back("hunter_S0_A");
  skinMap[18].push_back("hunter_S1_B");
  skinMap[18].push_back("hunter_S2_B");
  skinMap[18].push_back("hunter_S1_A");
  skinMap[18].push_back("hunter_S2_A");
  skinMap[18].push_back("hunter_S3");
  skinMap[18].push_back("hunter_S0_B");
  skinMap[19].push_back("ghostlord_S0_A");
  skinMap[19].push_back("ghostlord_S2_A");
  skinMap[19].push_back("ghostlord_S0_B");
  skinMap[19].push_back("ghostlord_S1_B");
  skinMap[19].push_back("ghostlord_S2_B");
  skinMap[19].push_back("ghostlord_S3");
  skinMap[19].push_back("ghostlord_S1_A");
  skinMap[20].push_back("ratcatcher_S0_A");
  skinMap[20].push_back("ratcatcher_S1_A");
  skinMap[20].push_back("ratcatcher_S0_B");
  skinMap[20].push_back("ratcatcher_S1_B");
  skinMap[20].push_back("ratcatcher_S2");
  skinMap[21].push_back("archeress_S0_A");
  skinMap[21].push_back("archeress_S4");
  skinMap[21].push_back("archeress_S5");
  skinMap[21].push_back("archeress_S6");
  skinMap[21].push_back("archeress_S7");
  skinMap[21].push_back("archeress_S1_A");
  skinMap[21].push_back("archeress_S2_A");
  skinMap[21].push_back("archeress_S3");
  skinMap[21].push_back("archeress_S0_B");
  skinMap[21].push_back("archeress_S1_B");
  skinMap[21].push_back("archeress_S2_B");
  skinMap[22].push_back("werewolf_S0_A");
  skinMap[22].push_back("werewolf_S3");
  skinMap[22].push_back("werewolf_S4");
  skinMap[22].push_back("werewolf_S1_A");
  skinMap[22].push_back("werewolf_S0_B");
  skinMap[22].push_back("werewolf_S1_B");
  skinMap[22].push_back("werewolf_S2");
  skinMap[23].push_back("frogenglut_S0_A");
  skinMap[23].push_back("frogenglut_S1_A");
  skinMap[23].push_back("frogenglut_S2_A");
  skinMap[23].push_back("frogenglut_S0_B");
  skinMap[23].push_back("frogenglut_S1_B");
  skinMap[23].push_back("frogenglut_S2_B");
  skinMap[24].push_back("witchdoctor_S0_A");
  skinMap[24].push_back("witchdoctor_S2");
  skinMap[24].push_back("witchdoctor_S1_A");
  skinMap[24].push_back("witchdoctor_S0_B");
  skinMap[24].push_back("witchdoctor_S1_B");
  skinMap[25].push_back("manawyrm_S0_A");
  skinMap[25].push_back("manawyrm_S1_A");
  skinMap[25].push_back("manawyrm_S0_B");
  skinMap[25].push_back("manawyrm_S1_B");
  skinMap[25].push_back("manawyrm_S2");
  skinMap[25].push_back("manawyrm_S3");
  skinMap[25].push_back("manawyrm_S4");
  skinMap[26].push_back("bard_S0_A");
  skinMap[26].push_back("bard_S2");
  skinMap[26].push_back("bard_S0_B");
  skinMap[26].push_back("bard_S1_B");
  skinMap[26].push_back("bard_S1_A");
  skinMap[27].push_back("naga_S0_B");
  skinMap[27].push_back("naga_S3");
  skinMap[27].push_back("naga_S1_A");
  skinMap[27].push_back("naga_S1_B");
  skinMap[27].push_back("naga_S2");
  skinMap[27].push_back("naga_S4");
  skinMap[27].push_back("naga_S0_A");
  skinMap[28].push_back("mage_S0_A");
  skinMap[28].push_back("mage_S1_B");
  skinMap[28].push_back("mage_S2");
  skinMap[28].push_back("mage_S4");
  skinMap[28].push_back("mage_S1_A");
  skinMap[28].push_back("mage_S2");
  skinMap[28].push_back("mage_S3");
  skinMap[28].push_back("mage_S0_B");
  skinMap[29].push_back("fairy_S0_A");
  skinMap[29].push_back("fairy_S1_B");
  skinMap[29].push_back("fairy_S2");
  skinMap[29].push_back("fairy_S0_B");
  skinMap[29].push_back("fairy_S1_A");
  skinMap[30].push_back("witcher");
  skinMap[30].push_back("witcher_S1");
  skinMap[30].push_back("witcher_S2");
  skinMap[30].push_back("witcher_S3");
  skinMap[30].push_back("witcher");
  skinMap[31].push_back("alchemist");
  skinMap[31].push_back("alchemist_S1");
  skinMap[32].push_back("demonolog");
  skinMap[32].push_back("demonolog_S2");
  skinMap[32].push_back("demonolog_S1");
  skinMap[33].push_back("vampire_S0_A");
  skinMap[33].push_back("vampire_S1_A");
  skinMap[33].push_back("vampire_S0_B");
  skinMap[33].push_back("vampire_S1_B");
  skinMap[33].push_back("vampire_S3");
  skinMap[33].push_back("vampire_S4");
  skinMap[33].push_back("vampire_S2");
  skinMap[34].push_back("witch_S0_A");
  skinMap[34].push_back("witch_S0_B");
  skinMap[34].push_back("witch_S1_B");
  skinMap[34].push_back("witch_S2_B");
  skinMap[34].push_back("witch_S1_A");
  skinMap[34].push_back("witch_S2_A");
  skinMap[34].push_back("witch_S3");
  skinMap[35].push_back("crusader_A");
  skinMap[35].push_back("crusader_S3_A");
  skinMap[35].push_back("crusader_S1_A");
  skinMap[36].push_back("crusader_B");
  skinMap[36].push_back("crusader_S2_B");
  skinMap[37].push_back("monster_S0_A");
  skinMap[37].push_back("monster_S0_B");
  skinMap[37].push_back("monster_S1_B");
  skinMap[37].push_back("monster_S1_A");
  skinMap[37].push_back("monster_S2");
  skinMap[38].push_back("angel");
  skinMap[38].push_back("angel_S2");
  skinMap[38].push_back("angel");
  skinMap[38].push_back("angel_S1_A");
  skinMap[39].push_back("freeze");
  skinMap[39].push_back("freeze_S2");
  skinMap[39].push_back("freeze");
  skinMap[39].push_back("freeze_S1");
  skinMap[40].push_back("gunslinger");
  skinMap[40].push_back("gunslinger_S1");
  skinMap[40].push_back("gunslinger_S2");
  skinMap[40].push_back("gunslinger_S3");
  skinMap[40].push_back("gunslinger");
  skinMap[41].push_back("reaper");
  skinMap[41].push_back("reaper");
  skinMap[41].push_back("reaper_S1");
  skinMap[41].push_back("reaper_S2");
  skinMap[42].push_back("fluffy");
  skinMap[42].push_back("fluffy_S1");
  skinMap[43].push_back("rifleman");
  skinMap[43].push_back("rifleman_S1");
  skinMap[44].push_back("magicgirl");
  skinMap[44].push_back("magicgirl_S1");
  skinMap[45].push_back("pinkgirl");
  skinMap[45].push_back("pinkgirl_S1");
  skinMap[46].push_back("ironknight");
  skinMap[46].push_back("ironknight_S1");
  skinMap[46].push_back("ironknight_S2");
  skinMap[47].push_back("fallenangel");
  skinMap[47].push_back("fallenangel_S2");
  skinMap[47].push_back("fallenangel_S1");
  skinMap[48].push_back("bladedancer");
  skinMap[48].push_back("bladedancer_S1");
  skinMap[49].push_back("ent");
  skinMap[49].push_back("ent_S1");
  skinMap[50].push_back("plaguedoctor");
  skinMap[50].push_back("plaguedoctor_S1");
  skinMap[50].push_back("plaguedoctor_S2");
  skinMap[50].push_back("plaguedoctor_S3");
  skinMap[51].push_back("katana");
  skinMap[51].push_back("katana_S1");
  skinMap[52].push_back("plane");
  skinMap[52].push_back("plane_S1");
  skinMap[53].push_back("zealot");
  skinMap[53].push_back("zealot_S1");
  skinMap[54].push_back("wraithking");
  skinMap[54].push_back("wraithking_S1");
  skinMap[55].push_back("dryad");
  skinMap[55].push_back("dryad_S1");
  skinMap[56].push_back("stalker");
  skinMap[56].push_back("stalker_S1");
  skinMap[57].push_back("gunner");
  skinMap[57].push_back("gunner_S1");
  skinMap[58].push_back("chronicle");
  skinMap[58].push_back("chronicle_S1");
  skinMap[59].push_back("brewer");
  skinMap[59].push_back("brewer_S1");
  skinMap[60].push_back("shadow");
  skinMap[60].push_back("shadow_S1");
  skinMap[61].push_back("wendigo");
  skinMap[61].push_back("wendigo_S1");
  skinMap[62].push_back("trickster");
  skinMap[62].push_back("trickster_S1");
  skinMap[63].push_back("banshee");
  skinMap[63].push_back("banshee_S1");
  skinMap[64].push_back("shaman");
  skinMap[64].push_back("shaman_S1");
  skinMap[65].push_back("bomber");
  skinMap[65].push_back("Bomber_S1");


  std::vector<std::string>& skins = skinMap[heroId];
  if (skins.empty()) {
    return "";
  }
  return skins[skinId % skins.size()];

}
} // namespace WebSession
